//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alimentos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Productos
    {
        public int Codigo { get; set; }
        public string Descripcion { get; set; }
        public int Valor { get; set; }
        public int Cantidad { get; set; }
        public int Categoria { get; set; }
    
        public virtual Categorias Categorias { get; set; }
    }
}
